# Nombre de tu proyecto
spring.application.name=2look-api

# URL de conexión (IMPORTANTE: He corregido el host al tuyo de Frankfurt)
spring.datasource.url=jdbc:postgresql://db.nhworkyardxoqmjrujrx.supabase.co:5432/postgres

# Usuario de la base de datos
spring.datasource.username=postgres

# Tu contraseña
spring.datasource.password=AlbaMartin3009!

spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect