spring:
  datasource:
    url: jdbc:postgresql://pg-5be4b5d-lookdatabase.i.aivencloud.com:17090/defaultdb?sslmode=require
    username: avnadmin
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  sql:
    init:
      mode: always

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
